### ISSUE TITLE
Specify License

### ISSUE THREAD

**Issue by mattt** [malcommac/DMInspectorPalette#1]
Could you please specify a software license for your project? Something like [MIT](http://opensource.org/licenses/mit-license) (and specifically non-GPL) would be great.

**Comment by malcommac** [comment]
There was an error in readme.md file (fixed). BTW it's MIT license. Thank you.

**Comment by mattt** [comment]
Awesome. Thanks for that. Looking forward to using this in @Induction :)

**Comment by malcommac** [comment]
that's a very interesting project, I'm honored to see my class in it :)
