### ISSUE TITLE
setState does not take into consideration the useAnimation flag

### ISSUE THREAD

**Issue by websecurify** [malcommac/DMInspectorPalette#15]
Thanks for the useful software. One small remark.

If you read - (void) setState:(DMPaletteState)state forSection:(DMPaletteSectionView *) targetSection animated:(BOOL)animate {

... you will notice that the function is invoked with with a static YES for the animated argument like this:

```
[self setState:state
   forSections:[NSIndexSet indexSetWithIndex:[contentSectionViews indexOfObject:targetSection]]
      animated:YES];
```

It should be like this:

```
[self setState:state
   forSections:[NSIndexSet indexSetWithIndex:[contentSectionViews indexOfObject:targetSection]]
      animated:animate];
```

Otherwise the useAnimation property will not be taken into consideration.

**Comment by malcommac** [comment]
Thank u, just fixed.
