### ISSUE TITLE
Extract Library Source Code & Move Example Project to Subdirectory

### ISSUE THREAD

**Issue by mattt** [malcommac/DMInspectorPalette#2]
A general convention for open source Objective-C projects is to have the library / framework source code in a top-level directory named for the project, and then an example application in a separate directory.

So in this case, `DMPaletteContainer.{h,m}` and `DMPaletteSectionView.{h,m}` would be in the `DMInspectorPalette` directory, which would then be referenced from the example app in the `Example` directory.

**Comment by malcommac** [comment]
thank you matt :)
